<?php
require_once("funcao/codifica.php");
require_once("funcao/decodifica.php");
require_once("funcao/redireciona.php");
require_once("funcao/valida_cpfcnpj.php");
require_once("funcao/valida_login.php");
require_once("funcao/url_remove_arg.php");
require_once("funcao/mascara_cpfcnpj.php");
require_once("funcao/ext_cep.php");
require_once("funcao/valida_data.php");
require_once("funcao/ext_rfb_cpf.php");
require_once("funcao/ext_rfb_cnpj.php");
require_once("funcao/f_ppalavra_cxalta.php");

require_once("funcao/mysql_conecta.php");
require_once("funcao/mysql_prepara.php");
require_once("funcao/mysql_excecao.php");
require_once("funcao/mysql_log.php");
?>